version: '3'
services:
  etl-toolbox:
    container_name: etl-toolbox_container
    build: ./etl
    image: etl-toolbox_image
    volumes:
      - ./etl/notebooks:/home/jovyan
      - ./etl/data/tmp:/home/tmp
    ports:
      - '8888:8888'
    networks:
      - plse
 
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    #volumes:
    #  - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - plse
    restart: unless-stopped
    
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    #volumes:
    #   - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - plse
    restart: unless-stopped

  #   ui?
  #   api?
  #   redis/nginx?

networks:
  plse:
    driver: bridge